// ==UserScript==
// @name         Credible Metadata
// @namespace    http://tampermonkey.net/
// @version      1.0
// @grant        none
// ==/UserScript==

(function() {
  'use strict';
  // Expose the metadata on the global window
  window.CREDIBLE_METADATA = {
  "Service Type": {
    "112": "Psych Rehab",
    "113": "AMA Consent",
    "114": "AWS",
    "115": "BWAS",
    "116": "CAGE",
    "117": "Care Coordination",
    "118": "CIWA",
    "120": "AIMS CSR",
    "121": "Columbia",
    "123": "CC Mileage",
    "126": "Contact Attempt",
    "127": "Continued Stay Rev",
    "128": "COWS",
    "130": "Safety Plan",
    "131": "CSSA",
    "132": "DAST",
    "133": "Disc Guidance Policy",
    "134": "Discharge Summary",
    "135": "DLA 20 Adult",
    "136": "Documentation Only",
    "138": "Form Letter",
    "139": "Event Record",
    "140": "Food Program",
    "141": "Health Action Plan",
    "142": "Heath Risk Assess",
    "143": "Hosp Outreach",
    "144": "Hospital Liason",
    "145": "Int Monitor Log",
    "146": "Jail Liason",
    "149": "KDHE Emer Med Auth",
    "151": "KDHE Med Record",
    "152": "KDHE Permission",
    "153": "LEO Assist",
    "158": "License Disclosure",
    "160": "MAST",
    "161": "MAT Consent",
    "162": "Med Reconciliation",
    "165": "Transfer Exit Form",
    "166": "No Show/Cancel",
    "167": "ATC Orientation",
    "168": "Patient Assistance",
    "169": "Picture Release",
    "173": "Rate Adjustment",
    "174": "RecovGoalWorksheet",
    "175": "Referral",
    "176": "Release of Info",
    "178": "SED Determination",
    "179": "Detox Initial Screen",
    "180": "SOWS",
    "181": "SPMI Determination",
    "183": "Strengths Assess",
    "184": "SUD Residntl Request",
    "186": "Telehealth Consent",
    "187": "Telephone",
    "189": "Transportation",
    "190": "UA Event Record",
    "191": "Utilization Review",
    "193": "Waiver 3161",
    "194": "Waiver Annual Review",
    "195": "Waiver ICEF",
    "197": "Waiver Plan of Care",
    "199": "AWARE",
    "200": "Attendant Care",
    "201": "Case Conference - DR",
    "202": "Case Conf No Patient",
    "203": "Case Conf Patient",
    "204": "Comp Care OCK",
    "205": "TransitionalCare OCK",
    "206": "Cont Stay Screen",
    "207": "Court Competency",
    "208": "CPST",
    "209": "CPST Supportive Emp",
    "210": "CPST IDDT",
    "211": "CPST Strength Based",
    "212": "Crisis Mobile",
    "213": "Crisis Basic",
    "214": "Crisis Intermediate",
    "215": "Crisis Therapy",
    "216": "Crisis Interv QMHP",
    "217": "E&M Established",
    "218": "E&M New",
    "219": "Fam Tx with Client",
    "220": "Fam Tx No Client",
    "221": "Group Therapy",
    "222": "HAP Completion OCK",
    "223": "Health Promotion OCK",
    "224": "Ind Living",
    "225": "IndTherapy",
    "226": "Injection",
    "227": "IOP",
    "228": "xInteractive Complex",
    "229": "Intermediate",
    "230": "LEO Eval",
    "231": "Med Intake",
    "232": "Med Mgmt",
    "233": "Mem Fam Support OCK",
    "234": "MH Intake",
    "235": "MH Reform Screen",
    "236": "Overnight Boarding",
    "237": "Parent Support Group",
    "239": "Parent Support",
    "240": "PASRR",
    "241": "PCCM",
    "242": "Peer Support",
    "243": "Peer Support Group",
    "244": "Prof Res Fam Stab",
    "245": "PRTF CBST",
    "246": "Psych Testing",
    "247": "Grp Pyschosocial",
    "248": "Indv Psychosocial",
    "250": "Reintegration",
    "251": "Respite",
    "252": "Social Detox",
    "253": "SUD Intake",
    "254": "SUD Support Services",
    "255": "TCM",
    "256": "Wrap Around",
    "260": "Peer Review",
    "261": "Initial Tx Pln",
    "262": "Init Tx Pln Fam W",
    "263": "Tx Plan Review",
    "265": "Init Tx Pln Fam WO",
    "266": "Tx Plan Review Fam W",
    "267": "Tx Plan ReviewFam WO",
    "269": "KSURS Admission",
    "270": "KSURS Discharge",
    "273": "eMAR Signatures",
    "274": "DLA 20 Youth",
    "275": "DLA 20 SUD",
    "276": "GAD-7",
    "277": "PHQ-9",
    "278": "PECFAS",
    "279": "CAFAS",
    "280": "IQ Evaluation",
    "281": "Med Box Filled",
    "282": "SUD ROI",
    "283": "Lab Orders",
    "285": "CSS Referral",
    "287": "SUD Discharge",
    "289": "E&M Telephone Only",
    "290": "SUD Transfer",
    "291": "Individual Counselng",
    "293": "DBT Group",
    "294": "Alpha Stim M w/Staff",
    "295": "AlphaStemAIDNo Staff",
    "296": "AlphaStemM No Staff",
    "297": "AlphaStimAID w/Staff",
    "299": "Correction MH Intake",
    "300": "Crisis HIS",
    "301": "NOMS",
    "302": "G NOMS",
    "303": "Community Liaison",
    "304": "Corrections Liaison",
    "305": "Vet Needs Assessment",
    "306": "Save Line Call",
    "307": "Waiver Assessment",
    "308": "AUDIT",
    "310": "MAT Referral",
    "311": "MAT Nurse Assessment",
    "312": "LPN Injection",
    "313": "Court SUD Intake",
    "314": "Admin Scoring Profes",
    "315": "Intake Assessment",
    "316": "Columbia Lst Contact",
    "317": "Overdose Suicide Att",
    "318": "Care Coordination Cr",
    "319": "Columbia Initial Tes",
    "320": "Columbia Last 48 Hrs",
    "321": "Modified MH Intake",
    "322": "Nav Note",
    "323": "HIS MHR Screen",
    "324": "Triage Intake",
    "325": "ROI Dr Office",
    "326": "AIMS New Client",
    "329": "SUD Ind Therapy",
    "331": "SUD Group Therapy",
    "337": "Supported Housing",
    "338": "SBIRT Intervention",
    "339": "Tobacco Cesation Ind",
    "340": "Tobacco Cesation Grp",
    "341": "MAT Injection",
    "342": "Crisis Referral",
    "344": "LEO Raw No Printing",
    "345": "Return of Property",
    "350": "Mixed Group",
    "351": "Rescreen MHR",
    "352": "ACT Housing Asessmnt",
    "353": "ACT Nurse Assessment",
    "354": "ACT IPS Assessment",
    "355": "ACT Peer Assessment",
    "356": "ACT Strengths Assess",
    "357": "ROI KDADS MCOs",
    "358": "ROI Pharmacy Multi",
    "359": "ROI Family Friends",
    "360": "ROI Medical Multi",
    "361": "ROI Pharmacy Indiv",
    "362": "ROI Emerg Contact",
    "363": "ROI Legal",
    "364": "ROI Hospital",
    "365": "SUD Registration",
    "366": "SUD License Disc",
    "367": "Check In",
    "368": "IPS Supported Employ",
    "369": "Referral - External",
    "370": "Caring Contact",
    "371": "Tech Scoring",
    "372": "Comp Restoration",
    "374": "Reception Doc Only",
    "377": "OSS Admission",
    "379": "CRAFFT",
    "380": "HIS Saveline Call",
    "381": "Discharg Chld Crisis",
    "382": "Restoration Complete",
    "383": "WRH Orientation",
    "384": "AIMS Movement Scale",
    "385": "CC Documentation",
    "386": "Tobacco Assessment",
    "387": "OP SUD Registration",
    "388": "Crisis Advanced",
    "390": "ROI Employer",
    "391": "TTS Dischrge Summary",
    "392": "IPS Sample Note NB",
    "393": "CSS Discharge",
    "394": "Chnge of Primary Emp",
    "395": "CBS Discharge",
    "396": "Pburg Crt ROI",
    "397": "BH Justice Discharge",
    "398": "Jail Therapy",
    "400": "Transfer Request",
    "401": "Carelon Eligibility",
    "402": "SUD Peer Support",
    "403": "SUD Peer Group",
    "404": "Waiver Needs Assmt",
    "405": "ROI Referring Agency",
    "406": "Pre Hospitalization",
    "407": "Injection Outside",
    "408": "Medication Drop Off",
    "409": "Referal Med Drop Off",
    "410": "Discharge Med Drop",
    "411": "Social Deter Hlth",
    "412": "ROI CHC",
    "413": "Prnt Peer Suport Ind",
    "414": "Prnt Peer Suport Grp",
    "415": "Handbook Discovery",
    "416": "Jail Group",
    "417": "Peer Support Res",
    "418": "RN E&M",
    "419": "School Ind Therapy",
    "421": "ROI Voc Rehab",
    "423": "Discharge Letter",
    "424": "Z15 Minute JIT",
    "425": "Com Health Worker",
    "426": "PG Soc Detox Consent",
    "427": "zStacey 911",
    "428": "Contact Attempt-Med",
    "429": "Portal Registration",
    "430": "zTeds Admission",
    "431": "zTeds Discharge",
    "440": "Care Coord Pat Nav",
    "9998": "Residential",
    "9999": "Core Export",
    "--": "Expired Types --"
  },
  "Billing Group": {
    "1": "OLD CMHC",
    "2": "OLD CCBHC",
    "5": "CCBHC",
    "6": "CMHC"
  },
  "Ledger Type": {
    "1": "BATCHED CLAIM",
    "2": "CLIENT PAYMENT",
    "3": "DISALLOWED",
    "4": "INS PAYMENT",
    "5": "INS PAYMENT RETRACTION",
    "8": "PENDING",
    "9": "REJECT CLAIM",
    "10": "REJECT SERVICE",
    "11": "RESUBMIT CLAIM",
    "12": "RESUBMIT SERVICE",
    "13": "SERVICE ADJUSTMENT",
    "15": "SERVICE RATE CHANGE",
    "17": "TRANSFER INS TO CLIENT",
    "22": "COPAY ADJUSTMENT",
    "23": "OTHERDUE ADJUSTMENT",
    "39": "INSURANCE CHANGE",
    "43": "PENDING ADJUSTMENT",
    "44": "TRANSFER INSURANCE",
    "70": "PATIENT RESPONSIBILITY",
    "75": "SERVICE RATE ADJUSTMENT",
    "80": "BATCHED BY CLAIM GROUPING",
    "81": "PATIENT UNCOLLECTABLE",
    "1001": "WRITEOFF",
    "1002": "LIABILITY",
    "1003": "OVER PAYMENT",
    "1004": "CONTRACT RATE",
    "1005": "OTHER",
    "1008": "NON-BILLABLE",
    "1011": "Timely Filing",
    "1012": "No Authorization",
    "1013": "Pro Bono",
    "1014": "Bad Debt",
    "1019": "Eligibility",
    "1021": "Interest",
    "1023": "DEBT SETOFF",
    "1024": "Unsolicited Refund",
    "--Ledger": "Types--"
  },
  "Recipient": {
    "2": "ClientOnly",
    "3": "CollatOnly",
    "4": "FamOnly",
    "5": "Cli+Collat",
    "6": "Cli+Fam",
    "7": "Cli+Col+Fm",
    "8": "Telephone"
  },
  "Team": {
    "2": "OP MH Adult",
    "3": "OP MH Child",
    "5": "Crisis",
    "6": "OP Med",
    "7": "OneCare",
    "10": "Community Support Svcs",
    "11": "Community Based Svcs",
    "12": "OP SUD",
    "13": "IOP",
    "14": "Community Correction",
    "15": "Crisis Community Outreach",
    "18": "Challenger",
    "19": "Discovery",
    "20": "Social Detox",
    "21": "ATC Intermediate",
    "22": "ATC Reintegration",
    "25": "Psych Test",
    "27": "WRH Reintegration",
    "28": "Intake",
    "29": "IPS",
    "30": "ACT",
    "31": "Veteran Services",
    "32": "Waiver",
    "33": "PRTF Authorization",
    "34": "Jail",
    "35": "Admin",
    "36": "Children Crisis Unit",
    "37": "MAT",
    "38": "TLC",
    "39": "Out of School Support",
    "40": "SUD Residential",
    "41": "WRH Intermediate",
    "42": "Tobacco Cessation",
    "43": "BH Justice",
    "44": "Med Route",
    "45": "Patient Navigator",
    "46": "Peer Support Adult",
    "47": "Autism"
  },
  "Program": {
    "6": "OP MH Adlt",
    "7": "OP MH Chld",
    "8": "OP Med",
    "9": "CSS",
    "10": "OneCare",
    "11": "Crisis",
    "12": "Challenger",
    "13": "CBS",
    "14": "Discovery",
    "15": "OP SUD",
    "16": "Soc Detox",
    "17": "ATC Interm",
    "18": "ATC Reint",
    "20": "IOP",
    "22": "Intake",
    "23": "Psych Test",
    "24": "ComCorr",
    "25": "CrisComOut",
    "26": "AIMS",
    "27": "S Detox P",
    "29": "Interm P",
    "30": "IOP P",
    "31": "OP SUD P",
    "32": "Reint P",
    "33": "WRH Reint",
    "34": "IPS",
    "35": "ACT",
    "36": "VetService",
    "37": "Waiver",
    "38": "PRTF Auth",
    "39": "Jail",
    "40": "Admin",
    "41": "ChCrisUnit",
    "42": "MAT",
    "43": "TLC",
    "44": "OSS",
    "45": "SUD Res",
    "46": "WRH Interm",
    "47": "IntermWR P",
    "48": "Tobacco",
    "49": "BHJustice",
    "50": "Med Route",
    "51": "Pt Nav",
    "52": "Peer Sup",
    "53": "Autism"
  },
  "Payer": {
    "2": "UNITED OPTUM MEDICAID",
    "3": "TRICARE WEST CLAIMS DEPT 00179",
    "4": "MEDICARE",
    "5": "AETNA MEDICAID",
    "6": "CGI",
    "7": "MEDIPLUS",
    "8": "H H HEALTH ASSOCIATES",
    "9": "CORPORATE PLAN MANAGEMENT INC",
    "10": "THE UNIVERSITY OF KANSAS MEDIC",
    "11": "AMERICAN HEALTHCARE ALLIANCE",
    "12": "CBH",
    "13": "GALLAGHER BASSETT SERVICES",
    "14": "WICHITA VA",
    "15": "RR Medicare",
    "16": "QUAPAW TRIBE OF OKLAHOMA",
    "17": "ComPsych",
    "18": "WPPA PROVIDERS CARE NETWORK",
    "19": "COX HEALTH PLAN",
    "20": "NGS",
    "21": "MHS",
    "22": "MERCY HEALTH PLANS",
    "23": "DALLAS NATIONAL INSURANCE COMP",
    "24": "WPS TRIWEST CMS 1500",
    "25": "KANSAS CARE THROUGH HOUSING KU",
    "26": "MEDICO INSURANCE COMPANY",
    "27": "PROGRESSIVE NORTHWESTERN INS",
    "28": "SENTINEL SECURITY",
    "29": "FREEDOM CLAIMS MANAGEMENT INC",
    "30": "EPSI",
    "31": "BANKERS FIDELITY",
    "32": "WPS VACAA",
    "33": "COUNTYCARE",
    "34": "OLD SURETY LIFE INS CO",
    "35": "FARMERS INSURANCE",
    "36": "HEALTHCARE HIGHWAYS H P",
    "37": "THE HARTFORD",
    "38": "KCVA",
    "39": "STATE FARM",
    "40": "MED PAY",
    "41": "MINES AND ASSOCIATES",
    "42": "TRICARE EAST REGION",
    "43": "FRINGE BENEFIT GROUP",
    "44": "ALIERA HEALTHCARE MEC",
    "45": "FCMI",
    "46": "ACI",
    "47": "OK STATE EMPLOYEES EDUCATORS",
    "48": "UPMC HEALTH PLAN",
    "49": "STUDENT INS NO CHARGE",
    "50": "Coventry Healthcare of Kansas",
    "51": "AETNA MEDICARE SUPPLEMENT",
    "52": "EMPLOYEE BENEFIT MANAGEMENT SE",
    "53": "CENTRAL RESERVE LIFE INS CO",
    "54": "CORESOURCE OF OHIO",
    "55": "CONTINENTAL BENEFITS",
    "56": "UHC AARP",
    "57": "CBA",
    "58": "KEY BENEFIT ADMINISTRATORS INC",
    "59": "EMPLOYEE BENEFIT CONSULTANTS I",
    "60": "HEALTHSMART BENEFIT SOLUTIONS",
    "61": "ALLIED BENEFIT SYSTEMS INC",
    "62": "CORENGS",
    "63": "TRICARE Champus PGBA",
    "64": "FISERV HEALTH WAUSAU BENEFITS",
    "65": "TIME INSURANCE COMPANY",
    "66": "MERITAIN HEALTH",
    "67": "American Republic Insurance",
    "69": "HEALTH PLANS INC",
    "70": "SISCO",
    "71": "AVERA HEALTH PLANS",
    "72": "Blue Cross Blue Shield Kansas",
    "73": "Blue Select",
    "74": "Premier Blue",
    "75": "PYRAMID LIFE INSURANCE COMPANY",
    "76": "ProviDRs Care Network",
    "77": "FMH BENEFIT SERVICES 48117",
    "78": "GROUP AND PENSION ADMIN 48143",
    "80": "CRAWFORD COUNTY EAP",
    "81": "NTCA BENEFITS",
    "82": "UMWA H R Funds",
    "83": "Lumenos Inc",
    "84": "Corporate Benefit Services",
    "85": "GEHA",
    "86": "AETNA MEDICARE",
    "87": "Harrington Benefit Services In",
    "88": "Mega Life & Health Insurance C",
    "89": "AETNA COMMERCIAL",
    "90": "Preferred Health Systems224",
    "91": "Preferred Plus of Kansas263",
    "92": "Humana Insurance Co Choice Ca",
    "93": "HUMANA MILITARY TRICARE SOUTH",
    "94": "FISERV",
    "95": "CIGNA",
    "96": "US HEALTH GROUP",
    "97": "BCBS MEDICARE ADVANTAGE CLAIMS",
    "98": "SUNFLOWER MEDICAID",
    "99": "ALLWELL WELLCARE",
    "100": "AMBETTER",
    "101": "KANSAS HEALTH ADVANTAGE",
    "102": "RURAL CARRIER BENEFIT PLAN",
    "104": "The Mega Life and Health Ins",
    "105": "WEB TPA CHEC",
    "106": "CARE IMPROVEMENT PLUS",
    "107": "UMR",
    "108": "ALL SAVERS",
    "109": "CHAMPVA",
    "110": "INSURERS ADMINISTRATIVE CORP",
    "111": "UPREHS",
    "112": "FIRST HEALTH",
    "113": "United Healthcare Medicare",
    "114": "MEDICA",
    "115": "THE HEALTH PLAN",
    "116": "FLEXASSURE SERVICE CENTER",
    "117": "BEACON HEALTH OPTIONS, INC",
    "118": "GLOBAL HEALTH",
    "119": "HCC MEDICAL INS SERVICES",
    "120": "MHNET",
    "121": "WPS TriWest Region",
    "122": "VA CCN OPTUM",
    "123": "Sunflower SED Waiver",
    "124": "Self Pay",
    "128": "KMAP QMB",
    "130": "City of Pittsburg- EAP",
    "131": "New Directions - EAP",
    "132": "SB123",
    "133": "Amfirst Insurance Company",
    "138": "United Healthcare Commercial",
    "139": "KMAP",
    "141": "KMAP MediKan",
    "143": "LUMICO MEDICARE SUPP",
    "145": "Luminare -Trustmark",
    "146": "Aetna CCBHC",
    "147": "Sunflower CCBHC",
    "148": "United Optum CCBHC",
    "149": "Berkshire Hathaway GUARD",
    "150": "United Healthcare Commercial EAP",
    "152": "GRAVIE ADMINISTRATIVE SERVICES",
    "153": "VOC REHAB",
    "154": "SEK-CAP",
    "159": "KMAP CCBHC",
    "161": "Planned Administrators",
    "162": "Cigna Medicare Supp",
    "163": "Omaha Insurance Company",
    "164": "Auxiant",
    "166": "Aither Health",
    "167": "HealthPartners Admin",
    "171": "Thrivent",
    "172": "Reliance Standard",
    "173": "CMHC Interagency EAP",
    "174": "CCMHC EAP",
    "176": "Recovery Court Program",
    "178": "Imagine 360",
    "179": "Benefit Management Inc",
    "180": "Bankers Life",
    "181": "HealthyBlue CCBHC",
    "183": "HealthyBlue Medicaid",
    "184": "Pekin Life Insurance",
    "185": "BCBS Medicare Supplement",
    "186": "TransAmerica Medicare Supplement",
    "187": "Office of Workers' Compensation",
    "188": "Medical Mutual - Cigna",
    "189": "AETNA EAP"
  },
  "Location": {
    "1": "Cent Ofc",
    "2": "Cent Tele",
    "3": "Cent CMHC",
    "4": "SUD NonResi",
    "5": "FACT Ofc",
    "6": "FACT Tele",
    "7": "FACT CMHC",
    "8": "FACT Home",
    "9": "FACT Other",
    "10": "Discovery Ofc",
    "11": "Discovery Tele",
    "12": "Discovery CMHC",
    "13": "Discovery Home",
    "14": "Discovery Othe",
    "15": "30th Ofc",
    "16": "30th Tele",
    "17": "30th CMHC",
    "18": "30th Home",
    "19": "30th Other",
    "20": "SUD NonResid",
    "21": "Whouse Ofc",
    "22": "Whouse Tele",
    "23": "Whouse CMHC",
    "24": "Whouse Home",
    "25": "WHouse Other",
    "26": "Whouse NonResi",
    "27": "WHouse Resid",
    "28": "ATC Ofc",
    "29": "ATC Tele",
    "30": "ATC CMHC",
    "31": "ATC Home",
    "32": "ATC Other",
    "33": "ATC NonResid",
    "34": "ATC Resid",
    "35": "Cent Tel Pt Hm",
    "36": "30th Tel Pt Hm",
    "37": "FACT Tel Pt Hm",
    "39": "ATC Tel Pt Hm",
    "40": "Whs Tele Pt Hm",
    "41": "Disc Tel Pt Hm",
    "42": "Cent Home",
    "43": "Mobile RV",
    "44": "Cent Other",
    "45": "Transport",
    "46": "Jail",
    "47": "School",
    "48": "School",
    "49": "Court",
    "50": "Broadway CMHC",
    "51": "Broadway Home",
    "52": "Broadway Ofc",
    "53": "Broadway Other",
    "54": "Bdwy Tel Pt Hm",
    "55": "Bdwy Telehelth",
    "56": "School",
    "--": "GEOAREAS --",
    "ga4": "30th",
    "ga6": "ATC",
    "ga7": "Broadway",
    "ga1": "Centennial",
    "ga3": "Discovery",
    "ga2": "FACT",
    "ga5": "WomenHouse"
  },
  "Sort By 1": {
    "0": "selected Billable",
    "1": "Order - 1",
    "2": "Order - 2",
    "3": "Order - 3",
    "4": "Order - 4",
    "5": "Order - 5",
    "6": "Order - 6",
    "7": "Order - 7",
    "8": "Order - 8",
    "9": "Order - 9",
    "10": "Ins Full Paid",
    "11": "Sequence - 1",
    "12": "Sequence - 2",
    "13": "Sequence - 3",
    "14": "Sequence - 4",
    "15": "Valid Auth",
    "17": "Has Attachments",
    "18": "Manual RedX",
    "date_batched": "Batch Date",
    "billing_group_name": "Billing Group",
    "cptcode": "CPT Code",
    "cpt_modifier": "CPT Modifier",
    "client_name": "Client Name",
    "duration": "Duration",
    "ename": "Employee",
    "location_code": "Location",
    "manual_redx": "Manual Red X",
    "payer_code": "Payer",
    "program_code": "Program",
    "timein": "Service Date",
    "visittype": "Service Type",
    "status": "Status",
    "-Date": "Type-",
    "VISITDATE": "Service Date",
    "TRANSFERDATE": "Transfer Date",
    "APPRDATE": "Approval Date",
    "LEDGERDATE": "Ledger Posting",
    "Used": "with the - Payer - sort to determine whether to search for services that have this payer as the primary, current, or any association.",
    "primary": "selected Primary Payer",
    "current": "Current Payer",
    "any": "Any Payer",
    "The": "billing order in the insurance record that the service is currently at.  Sequence is the ordinal sequence that the insurances are billed out to in succession.",
    "--": "Sequence --"
  },
  "Sort By 2": {
    "date_batched": "Batch Date",
    "billing_group_name": "Billing Group",
    "cptcode": "CPT Code",
    "cpt_modifier": "CPT Modifier",
    "client_name": "Client Name",
    "duration": "Duration",
    "ename": "Employee",
    "location_code": "Location",
    "manual_redx": "Manual Red X",
    "payer_code": "Payer",
    "program_code": "Program",
    "timein": "Service Date",
    "visittype": "Service Type",
    "status": "Status"
  },
  "Status": {
    "COMPLETED": "COMPLETED",
    "BATCHED": "BATCHED",
    "RESUBMIT": "RESUBMIT",
    "REJECTED": "REJECTED",
    "PENDING": "PENDING",
    "PAID": "PAID",
    "TRANSFERRED": "TRANSFERRED",
    "RECONCILED": "RECONCILED",
    "RETRACTED": "RETRACTED",
    "ALLBILLED": "ALL BILLED",
    "OPENCLAIM": "ALL OPEN CLAIM",
    "ALLRECONCILED": "ALL RECONCILED",
    "Returns": "all services with an age date greater than this number of days old (ie. 30, 60, 90)"
  },
  "Payer Type": {
    "15": "MEDICAID",
    "16": "MEDICARE",
    "17": "COMMERCIAL",
    "18": "STATE FUNDED A&D",
    "19": "SELF PAY",
    "20": "Waiver",
    "21": "EAP",
    "22": "CCBHC",
    "23": "SPECIAL BILLING"
  }
};
})();  
